add_fileset_file altera_ai_ip/dla_dma_param.svh SYSTEM_VERILOG_INCLUDE PATH ../altera_ai_ip/verilog/AGX5_Streaming_Ddrfree_Softmax_AGX5/dla_dma_param.svh
add_fileset_file altera_ai_ip/dla_dma_csr_discovery_rom.mif MIF PATH ../altera_ai_ip/verilog/AGX5_Streaming_Ddrfree_Softmax_AGX5/dla_dma_csr_discovery_rom.mif
add_fileset_file altera_ai_ip/dla_interface_profiling_counters.mif MIF PATH ../altera_ai_ip/verilog/AGX5_Streaming_Ddrfree_Softmax_AGX5/dla_interface_profiling_counters.mif
add_fileset_file altera_ai_ip/dla_top_wrapper_AGX5_Streaming_Ddrfree_Softmax_AGX5.sv SYSTEM_VERILOG PATH ../altera_ai_ip/verilog/AGX5_Streaming_Ddrfree_Softmax_AGX5/dla_top_wrapper_AGX5_Streaming_Ddrfree_Softmax_AGX5.sv
