
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE25_NANO(

	//////////// CLOCK //////////
	input 		          		CLOCK1_50,
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,

	//////////// KEY //////////
	input 		     [1:0]		KEY,

	//////////// LED //////////
	output		     [7:0]		LED,

	//////////// SW //////////
	input 		     [3:0]		SW,

	//////////// UART //////////
	input 		          		FPGA_UART_RX,
	output		          		FPGA_UART_TX,

	//////////// MIPI CAM //////////
	input 		          		CAM_CLK_n,
	input 		          		CAM_CLK_p,
	input 		     [1:0]		CAM_D_n,
	input 		     [1:0]		CAM_D_p,
	inout 		          		CAM_GPIO,
	inout 		          		CAM_I2C_SCL,
	inout 		          		CAM_I2C_SDA,
	input 		          		CAM_RZQ1
);



//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================



endmodule
